# If you like this file, rename it to `config.yaml` and place it in
# `~/.config/image2ascii/` (if you're running Linux, that is ... if not,
# you're on your own).
border: true
char_ratio: 0.469
color:
  background: black
  border: brightblack
  converter: rgb
  inference: median
crop: true
effect:
  brightness: 1.0
  contrast: 1
  invert: false
  sharpness: 1.0
margins: 1
min_likeness: 0.9
quality: 5
resample: NEAREST
shapeset: default
transparency:
  alpha: 128
  bg_distance: 150
  brightness: 48
  disable: false
  force_brightness: false
  methods:
  - brightness
  - bgdistance
  - alpha
viewport:
  columns: 120
  rows: 50
