[project]
name = "image2ascii"
version = "0.11.0"
description = "Turns images into ASCII art. This is just the core library; make sure to install some extras, too."
readme = "README.md"
authors = [
    { name = "Robert Huselius", email = "robert@huseli.us" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "platformdirs>=4.9.6",
    "pydantic>=2.13.1",
    "pydantic-settings>=2.13.1",
    "requests>=2.33.1",
]
license = "GPL-3.0-only"
license-files = ["LICENSE"]

[project.optional-dependencies]
svg = [
    "cairosvg>=2.9.0",
]
cli = [
    "image2ascii-cli",
]
emoji = [
    "image2ascii-emoji",
]
tui = [
    "image2ascii-tui",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "packages/cli",
    "packages/emoji",
    "packages/tui",
]

[tool.uv.sources]
image2ascii-cli = { workspace = true }
image2ascii-emoji = { workspace = true }
image2ascii-tui = { workspace = true }

[dependency-groups]
dev = [
    "image2ascii-cli",
    "image2ascii-emoji",
    "image2ascii-tui",
    "ipdb>=0.13.13",
    "ipython>=9.12.0",
    "ruff>=0.15.10",
    "ty>=0.0.31",
]

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [".venv", ".git", ".mypy_cache", "__pycache__", "build", "node_modules", "scratch.py"]
show-fixes = true

[tool.ruff.lint]
select = ["E", "F", "W", "B", "I"]
ignore = ["E722", "B027"]

[tool.ruff.lint.isort]
lines-after-imports = 2
combine-as-imports = true
default-section = "third-party"
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.format]
quote-style = "double"
docstring-code-line-length = 80
