__version__ = "0.4.9"

VERSION = tuple(map(int, __version__.split(".")))
DEFAULT_ASCII_RATIO = 2.0
DEFAULT_ASCII_WIDTH = 80
DEFAULT_QUALITY = 5
DEFAULT_MIN_LIKENESS = 0.9
EMPTY_CHARACTER = " "
FILLED_CHARACTER = "$"
